# Generated by Django 3.0.5 on 2020-11-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0005_auto_20201109_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_full_name', models.CharField(max_length=200)),
                ('work_email', models.EmailField(max_length=200)),
                ('work_phone', models.CharField(max_length=20)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('department_role', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('public_display', models.BooleanField()),
            ],
            options={
                'ordering': ('-staff_full_name',),
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=40)),
                ('voucher_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-voucher_type',),
            },
        ),
        migrations.AddField(
            model_name='products',
            name='no_of_sales',
            field=models.IntegerField(default=0),
        ),
    ]
