# Generated by Django 3.0.5 on 2020-11-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0006_auto_20201109_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='no_of_sales',
            field=models.IntegerField(default='0'),
        ),
    ]
