# Generated by Django 3.0.5 on 2020-11-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0007_auto_20201110_1954'),
        ('IT6041App', '0007_auto_20201111_1232'),
    ]

    operations = [
    ]
