# Generated by Django 3.0.5 on 2020-11-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0008_merge_20201112_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='popular',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='no_of_sales',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
