# Generated by Django 3.0.5 on 2020-11-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0008_merge_20201119_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('-staff_full_name',), 'verbose_name_plural': 'Staff Members'},
        ),
    ]
