# Generated by Django 3.0.5 on 2020-11-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0009_auto_20201123_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='date_added',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
