# Generated by Django 3.0.5 on 2020-11-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0010_auto_20201123_1809'),
        ('IT6041App', '0009_auto_20201119_2355'),
    ]

    operations = [
    ]
