# Generated by Django 3.0.5 on 2020-11-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0011_merge_20201129_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='carousel_listing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_code',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
