# Generated by Django 3.0.5 on 2020-12-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0012_auto_20201129_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('product_name',), 'verbose_name_plural': 'Products'},
        ),
    ]
