# Generated by Django 3.0.5 on 2020-11-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0012_auto_20201129_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.AutoField(default='', editable=False, primary_key=True, serialize=False),
        ),
    ]
