# Generated by Django 3.0.5 on 2020-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0013_auto_20201202_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('num_available', models.IntegerField(default=1)),
                ('num_used', models.IntegerField(default=0)),
            ],
        ),
    ]
