# Generated by Django 3.0.5 on 2020-12-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0015_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department_role',
            field=models.CharField(choices=[('A', 'Administrator'), ('S', 'Staff Member'), ('M', 'Marketing')], default='S', max_length=1),
        ),
    ]
